### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by IManAsap** [Nothing-Works/laravel-helper#1] opened 2020-06-05 09:59 UTC
With this command : andylaravel setupIDE
I have this result : 
  0/12 [>---------------------------]   0%PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/u1/.config/composer/vendor/andysong/laravel-helper/src/Processes/LaravelRoot.php on line 9

**Comment by Nothing-Works** [comment] 2020-06-06 00:35
@IManAsap I am not able to reproduce this bug, but I think the reason is that your PHP version is lower than 7.4. I would like to ask you to upgrade your PHP version and run this command again. I am going to close this issue for now if you still have problems let's continue to discuss here or feel free to fire another issue.

**Closed as completed by Nothing-Works** 2020-06-06 00:35 UTC
